### ISSUE TITLE
unnamed prepared statement does not exist

### ISSUE THREAD

**Issue by datacompboy** [mabrek/epgsql#1]
Here is original discussion: https://github.com/wg/epgsql/issues/19#issuecomment-6417211

epgsql:equery() sometimes get the error:
 {error,error,<<"26000">>, <<"unnamed prepared statement does not exist">>, []}
just re-send fixes it.

usage code:

``` erlang
q(Esql) ->
    case catch erlsql:sql(Esql) of
        {error, _} = Err ->
            throw(Err);
        Sql ->
            q2(Sql)
    end.

q2(Statement) ->
    q2(Statement, 2).

q2(_Statement, 0) ->
    {error, {error,error,<<"26000">>, <<"unnamed prepared statement does not exist">>, []}};

q2(Statement, N) ->
    case pgsql:equery(?MODULE, Statement) of
    {error, {error,error,<<"26000">>, _, _}} -> q2(Statement, N-1);
        {ok, _Cols, Rows} -> {ok, Rows};
        {ok, Count} -> {ok, Count};
        {ok, _Count, _Cols, Rows} -> {ok, Rows};
        {error, Error} -> {error, Error}
    end.
```

**Comment by datacompboy** [comment]
For testing removed repeat workaround and replaced equery with squery, will monitor

**Comment by mabrek** [comment]
Take a look at concurrent-equery branch, if it works for you I'll merge the fix into async

**Comment by datacompboy** [comment]
squery looks working -- at least, no errors for last 2 hours.
will check concurrent-equery soon

**Comment by datacompboy** [comment]
Yeah, concurrent-equery branch working stable, no errors thrown.

**Comment by datacompboy** [comment]
btw: what better to use -- squery or equery, when no arguments used?

**Comment by mabrek** [comment]
If you construct sql string every time and don't have parameters then it's better to use squery.
If you run same query with different parameters over and over again then it's better to parse it once and use bind/execute.

**Comment by datacompboy** [comment]
Agh... squery NOT option for me, since it doesn't decode binary.

**Comment by mabrek** [comment]
merged into async banch
