### ISSUE TITLE
Complex arguments to equery/3

### ISSUE THREAD

**Issue by dvv** [mabrek/epgsql#3]
Hi!

Given
`pgsql:squery(C, "select * from foo where id in (1, 2)")`
what would be the rewrite to have parameterized query?
Neither
`pgsql:equery(C, "select * from foo where id in ($1)", [[1, 2]])`
nor
`pgsql:equery(C, "select * from foo where id in ($1)", [{int8array, [1, 2]}])`
work.

TIA,
--Vladimir

**Comment by mabrek** [comment]
IN() doesn't play well with prepared statements, use =ANY() with arrays instead.

pgsql:equery(C, "select 5 = ANY($1)", [[1,2,3]]).
pgsql:equery(C, "select 3 = ANY($1)", [[1,2,3]]).

**Comment by dvv** [comment]
Thanks a lot!
